# Generated by Django 5.0.2 on 2024-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmler'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_adi',
            field=models.CharField(max_length=300),
        ),
    ]
