# Generated by Django 5.0.2 on 2024-03-05 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_alter_movie_film_adi'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='güncelleme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
